name: docker-buildx-push

on:
  push:
    branches:
      - main

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout master
        uses: actions/checkout@master
      -
        name: Build and publish image
        env:
          GHCR_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: zmingxie/docker_buildx@master
        with:
          publish: true
          imageName: ghcr.io/kavenci/nsimon:latest
          dockerHubUser: $GHCR_USERNAME
          dockerHubPassword: $GHCR_TOKEN
