name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Adjust to match your branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      id: qemu

    - name: Build and Push Docker Image
      env:
        GHCR_USERNAME: ${{ secrets.GITHUB_ACTOR }}
        GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/nsimon
        DOCKER_CLI_AARCH64_ARCH: arm64
        DOCKER_CLI_ARM_ARCH: arm
        DOCKER_CLI_PLATFORM: linux/arm64,linux/arm/v7,linux/arm/v6
        DOCKER_BUILDKIT: 1
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap

        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
          -t $DOCKER_IMAGE_NAME:latest \
          -t $DOCKER_IMAGE_NAME:$GITHUB_SHA \
          -t $DOCKER_IMAGE_NAME:$GITHUB_REF \
          -f Dockerfile .

        echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
        docker push $DOCKER_IMAGE_NAME:latest
        docker push $DOCKER_IMAGE_NAME:$GITHUB_SHA
        docker push $DOCKER_IMAGE_NAME:$GITHUB_REF
