name: docker-buildx-push

on:
  push:
    branches:
      - main

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout master
        uses: actions/checkout@master
      -
        name: Build and publish image
        uses: zmingxie/docker_buildx@master
        with:
          publish: true
          imageName: ghcr.io/kavenci/nsimon
          dockerHubUser: ${{ secrets.GITHUB_ACTOR }}
          dockerHubPassword: ${{ secrets.GITHUB_TOKEN }}
